### ISSUE TITLE
Add Nines Performance Tool & Images Article

### ISSUE THREAD

**Issue by derekshull** [danielguillan/perf.rocks#41]
Nines is a performance aimed to help developers find critical performance issues.  v2 supports RUM (using Navigation Timing & Resource Timing APIs) and Synthetic testing (using WebPageTest.org API).  You can see median site speed for your current view, overall from the info collected using RUM, and the median site speed for each country that's visited the site.

It also provides a list of resources and the time it took to load each resource, allowing the ability to pinpoint troublesome assets.  The tool show basic stats from WebPageTest.org (TTFB, Speed Index, Load Time, Document Size, etc.) and provides a break down of video frames to allow the user to see how the page loads.

It can be demoed at http://mattshull.com/perf and the code can be viewed at http://github.com/derekshull/nines

Also here's an article on image performance: http://blog.thinkful.com/post/103650638583/optimizing-your-images-make-your-website-load

**Comment by derekshull** [comment]
Category: performance analysis
Tags: navigation timing api, resource timing api, webpagetest

Side note: v3 will be rolling out in a couple of weeks and will support features that will allow users to track performance over time.  More to come!

**Comment by danielguillan** [comment]
Thank you very much Matt! I added both, Nines and your article on image performance.
