### ISSUE TITLE
People

### ISSUE THREAD

**Issue by derekshull** [danielguillan/perf.rocks#42]
Not sure if we can submit ourselves but I've created a performance tool, write performance posts, and I'm lined up this year to give a talk at 2 different events on web performance (Feb 10 & Oct TBD).

Bio: Matt Shull

Twitter: TheMattShull

Bio:
Matt is a performance nerd who loves experimenting with web technologies to boost efficiency.  He currently works at Aristotle Interactive and mentors FEWD and AngularJS students through Thinkful.  He hopes to share what he's learned "in the trenches" about web performance and cultivate a community that strives to make the web faster.

**Comment by derekshull** [comment]
I also mentor students in FEWD and Angular through Thinkful.com. My Twitter is mainly development and performance related tweets and retweets. I'm currently writing curriculum for the intensive FEWD at Thinkful and web performance is a section I'm working on.

**Comment by danielguillan** [comment]
I add people automatically when they have at least one article/talk/book listed on the site. So… you're now on the list! :tada: 

Thanks again for submitting!
