### ISSUE TITLE
Create section Case Studies

### ISSUE THREAD

**Issue by nucliweb** [danielguillan/perf.rocks#95]
Create a new section Case Studies with all items with category Case Studies in articles

**Comment by danielguillan** [comment]
Thanks for the suggestion! Could you please explain why you think this would be a good addition?

**Comment by nucliweb** [comment]
I think it's interesting to have grouped all the Case Studies in the same section.
And if you want, I can create this a new section for that ;)

**Comment by danielguillan** [comment]
In the next version of perf.rocks categories will become the main navigation and current sections (tools, videos, articles, …) will become filters of said categories. So there will be a main `Case Studies` section where you'll find articles, videos and more. :+1:
